### ISSUE TITLE
Question about lang file

### ISSUE THREAD

**Issue by FlameFire26** [jsorrell/CarpetSkyAdditions#116]
Is the 'carpetskyadditions.rule...' in lang file have settings in game or config files?
I translated it but to find no where to see them in game.

**Comment by jsorrell** [comment]
The `carpetskyadditions.rule.*` translations use the Carpet translations system (instead of the Minecraft one), so they only accept translations for Chinese (simplified and traditional) and Brazilian Portuguese. They use the `/carpet language` setting as described here: https://github.com/gnembon/fabric-carpet/wiki/Current-Available-Settings#language.

Also, translations from CrowdIn only update on a new release and some CrowdIn  changes haven't been released yet (https://github.com/jsorrell/CarpetSkyAdditions/pull/112).
