### ISSUE TITLE
Anyway to make the mod not required to play on the world?

### ISSUE THREAD

**Issue by Ka1nnn** [jsorrell/CarpetSkyAdditions#143]
Is there anyway i can generate a skyblock world but not have the mod be required to play on the world? I tried making a world and then removing the mod but it wont let me play on the world saying its missing some datapacks? And also it has happened to me that i tried to open a world download of a farm and it would not let me open it and kept saying the same error that some datapacks are missing even tho the world was not a sky block one, Also im sorry if this is not the right place for this type of question i searched for like a discord support but couldn't find one :( 

Essentially what i want is to be able to make a skyblock world and keep everything else vanilla MC i don't want any of the extra features or stuff and i want to be able to access the world without having to have the mod installed, because i might want to upload it somewhere or send it to a person and i don't want to have them be forced to install a mod to play on a world ig. 

![image](https://github.com/jsorrell/CarpetSkyAdditions/assets/136351694/50a82d31-dbc9-455f-83c0-49c9472992b6)

**Comment by jsorrell** [comment]
With the mod, you can disable all datapack features in the mod by disabling/not enabling the built in datapack. All mod features can be disabled using the `/carpetskyadditions` command or deleting `carpetskyadditions.conf` in the world folder. You can also customize which structures generate (if any) using the command.

While a SkyBlock world can be played without the mod, no new skyblock chunks can be generated because the mod contains the custom chunk generator `carpetskyadditions:skyblock`. "Errors in the data packs" cryptically means Minecraft is not finding the chunk generator. In order to fully remove the mod, you would have to pre-generate a large number of chunks (maybe with something like https://www.curseforge.com/minecraft/mc-mods/chunk-pregenerator-fabric) and save that world, then change chunk generators in the world's nbt file to a vanilla ones such as `minecraft:noise`. Pregenerating chunks may create a large save file, depending on the size of the area generated. This is how downloadable skyblock maps work -- if you were to travel over 10000 blocks or whatever in one direction, the chunks would generate like a normal world.

I believe it is possible to make a void world using purely datapacks, but I'm not sure how well it would work wrt biomes, structure bounding boxes, etc.

**Comment by Ka1nnn** [comment]
Darn i pressed the close issue button by mistake my bad... I wanted to say thank you for the explanation appreciate it! I have one more thing to ask and that is why wont some world downloads wont load with the mod installed??

[gold farm_xp_looting.zip](https://github.com/jsorrell/CarpetSkyAdditions/files/12677767/gold.farm_xp_looting.zip)
[hc7-iskal_golf_farm.zip](https://github.com/jsorrell/CarpetSkyAdditions/files/12677771/hc7-iskal_golf_farm.zip)

These are 2 example of worlds that wont load with the mod installed but will load with it removed, they are just world downloads from gnembon's gold farm, when i try to load them i get the same issue log with datapacks missing or something.

**Comment by jsorrell** [comment]
That sounds like a bug in the mod. I'll look into it.
