### ISSUE TITLE
A way to remove the nyliums in the spawn platform

### ISSUE THREAD

**Issue by YipKei** [jsorrell/CarpetSkyAdditions#42]
When a fungus grows on Mycelium in the correct biome in Nether, it can spread corresponding nylium on the netherrack nearby.

Then add a other way to get the first fungus. Maybe a Wandering Trader sell it, or Piglins give it when bartering, or zoglins rarely drop one.

It will be more common sense. Player can only get the Huge Crimson Fungus drops when they go to Nether.

**Comment by Anonym271** [comment]
Actually in the [first snapshots](https://minecraft.fandom.com/wiki/Bartering/Outdated_loot_tables_in_Java_Edition#20w09a) of the nether update Piglins were bartering Warped Nylium and Warped Fungus. Maybe it would be an idea to re-introduce this or something similar for Skyblock.

Another idea would be that instead of plain netherrack the Nylium version of the current biome would generate around mid-air Nether portals. Would actually be the best option in my opinion.

**Comment by jsorrell** [comment]
I like @Anonym271's last idea the most I think. It's a good change to gate the Nylium behind the Nether.

**Comment by YipKei** [comment]
Yes. His idea is better. It's as simple as the original way to get nylium, except it needs to enter the Nether.

**Comment by maruohon** [comment]
@jsorrell I implemented this feature in my fork. There is a new `renewableNylium` rule for this. It will generate one block on each side of the portal, corresponding to the biome at that block position.

If the `renewableNylium` rule is enabled (which it is by default in the sky block world type), then the mod also uses a separate spawn platform structure without the Nylium blocks. However I'm not sure how you are supposed to disable the rule before generating the world? Can you just add the rule conf file to the to-be world directory before creating the world?

I also have a couple of other commits in my branch, one of them updating from the old deprecated rules to the new Carpet API rules, and another commit that splits the dependency on the Fabric API to only the modules that are actually needed, and I also embed those as jar-in-jar.

I don't know if you want those changes, or even this feature as a PR. Let me know and I can create separate branches and PRs for the individual things.

In any case I'm going to use this version on my own server I'm about to start. And to that end I also have a commit that updates to 1.19.2, which was basically one method getting named. But in my branch I also disabled the entire `SchemasMixin` since I don't have old worlds to update at this point, and I didn't feel like figuring out if that mixin still works properly or needs some updates.

**Comment by jsorrell** [comment]
@maruohon You can change the worldgen rules before creating the world by adding the conf file early like you said. You could also try setting the rule and deleting the `region` directory to recreate the world, but its likely this wouldn't trigger the `spawnSetup` method and the spawn platform wouldn't be created. There's not really a great way to do it b/c carpet rules weren't designed for worldgen.

I've already implemented this issue's fix locally but I've neglected mod this for a little bit and haven't finished updating to the new Carpet API. I'll try to update this mod shortly and take a look at your fork to see if there's anything I want to merge. Thanks.

The `SchemasMixin` just enables the datafixers so it doesn't do anything unless the game version is updated so it should be fine to disable. Though if it compiles it should work as intended.
