### ISSUE TITLE
[Feature Request] Vanilla One Block Generator

### ISSUE THREAD

**Issue by Nolij** [jsorrell/CarpetSkyAdditions#52]
Do you enjoy pain? Then I have a challenge for you; https://www.youtube.com/watch?v=66q2bgLwWLs !

Seriously though, this series has been great fun to watch, and it seems like it would be a good fit for this mod.

**Comment by jsorrell** [comment]
That sound like an interesting challenge to watch, but terribly tedious to play.

It seems like the only change that's needed is a different initial spawn. This challenge seems to need a player to spawn on a single grass block that gets snowed on, preferable low in the world so there is a higher chance mobs spawn while falling into the void. Probably a Snowy Taiga b/c Foxes spawn there. Maybe at Y=-63 so Endermen can pick it up the grass block while standing on something. This block needs to be away from the worldspawn so mobs can spawn, but the player's spawnpoint must be set on it using something like the `/spawnpoint` command.

It's easy enough to set up such a spawn point in creative. If you're willing to spend the 100+ hours it would need just to get a 2nd block, it's probably worth planning your seed and spawnpoint more thoroughly than an automatic generator can.

**Comment by Nolij** [comment]
> That sound like an interesting challenge to watch, but terribly tedious to play.
> 
> It seems like the only change that's needed is a different initial spawn. This challenge seems to need a player to spawn on a single grass block that gets snowed on, preferable low in the world so there is a higher chance mobs spawn while falling into the void. Probably a Snowy Taiga b/c Foxes spawn there. Maybe at Y=-63 so Endermen can pick it up the grass block while standing on something. This block needs to be away from the worldspawn so mobs can spawn, but the player's spawnpoint must be set on it using something like the `/spawnpoint` command.
> 
> It's easy enough to set up such a spawn point in creative. If you're willing to spend the 100+ hours it would need just to get a 2nd block, it's probably worth planning your seed and spawnpoint more thoroughly than an automatic generator can.

The automatic generator comes in setting up the stronghold, but with only one room, and things like that.

**Comment by jsorrell** [comment]
What things specifically? I assume Pinu generates a stronghold with one room so there's an end portal frame and lava available, but this mod already makes those things available in its own way. He also leaves nether and end generation intact I think; this mod doesn't but every resource is still available. As far as I can tell, a one block playthrough should still be possible simply by changing the spawn platform.

**Comment by hippolytevalicon** [comment]
Wouldn't it be possible to slightly modify the spawn so it's 1 block instead at y = -64 (you don't need to move the grass block) and outside of spawn radius ? In a random biome
I tried to look into it with NBT explorer so I can custom the spawn myself but I'm not sure it would work

**Comment by jsorrell** [comment]
I threw together a datapack that should essentially do what you want. It spawns you 48 blocks from the worldspawn at y=-64 and expands the spawnRadius. All the features of the mod except worldgen are disabled (except lava comes from a wandering trader instead of at the stronghold b/c you can't really change that with a datapack).

There's one unintended bug that isn't easy to work around with just a datapack -- if an ancient city generates within the spawn chunks, the portal will still be generated b/c the mod's config doesn't get changed until the first tick of the world. Most of the time in this situation you will spawn in a deep dark biome anyway so the spawn will be unplayable. You can fix this with a default config file if you want.

Don't enable the standard datapack b/c that makes some changes from vanilla -- just enable this one.

[skyblock_oneblock.zip](https://github.com/jsorrell/CarpetSkyAdditions/files/9703867/skyblock_oneblock.zip)

**Comment by hippolytevalicon** [comment]
ty so much ! I'll try that right away (it's impossible to disable lava from wandering trader right?)

**Comment by hippolytevalicon** [comment]
It's working for me, on top of that I'd like to disable features from the skyblock mod itself, is that possible ? (maybe if I go in the mod folder and edit it manually?)

**Comment by jsorrell** [comment]
In the `data/skyblock/functions/setup_oneblock_spawn.mcfunction` file, there's a big list of commands disabling settings from this mod.
You can disable lava from the wandering trader by deleting the line `carpetskyadditions setDefault lavaFromWanderingTrader true` however, this will make it impossible to get Lava so no Stone, Nether, or the End. The only two settings from this mod left enabled are `generateEndPortals` and `generateSilverfishSpawners`. You can disable these if you want, but it looks like these typically generate in the oneblock challenge.

**Comment by hippolytevalicon** [comment]
nice, ty very much (I want to do a challenge without access to lava, only pure vanilla features where I get all the obtainable items, because I found a glitch that allows you to get professions you shouldn't get without access to stone using zombie villager curing, and the only way it's useful would be on a challenge with 0 access to lava)

**Comment by hippolytevalicon** [comment]
So I deleted the line "carpetskyadditions setDefault lavaFromWanderingTrader"
And added
carpetskyadditions removeDefault generateEndPortals
carpetskyadditions removeDefault generateSilverfishSpawners

This would work right ? So in the end I simply get a completely empty world with only vanilla features and 1 grass block (no access to lava/only structure boundary boxes), which is what I want

**Comment by jsorrell** [comment]
@hippolytevalicon The new lines should instead be `carpetskyadditions setDefault generateEndPortals false` and `carpetskyadditions setDefault generateSilverfishSpawners false` because those default to true.

**Comment by hippolytevalicon** [comment]
nice, ty for your help !

**Comment by jsorrell** [comment]
Here's the edited datapack for future reference:
[skyblock_oneblock.zip](https://github.com/jsorrell/CarpetSkyAdditions/files/9710203/skyblock_oneblock.zip)
