### ISSUE TITLE
CarpetSkyAdditions overwriting default carpet settings.

### ISSUE THREAD

**Issue by dododome01** [jsorrell/CarpetSkyAdditions#53]
Carpet has the option for default config files, which are used unless the world has its own config file. This feature also works on all Carpet addons.
CarpetSkyAddition generates its own config file into every world folder, removing the ability to have a custom default preset.
It also generates a new carpet config file with its required settings, removing carpets ability for such a configfile aswell.

I would suggest adding a default file into the config folder, instead of always generating a new one, aswell as only appending/changing the default carpet one instead of overwriting it.

**Comment by jsorrell** [comment]
The problem is that there are two separate sets of defaults in this mod -- one for SkyBlock worlds and one for other world types (where everything is disabled). This is to make it so this mod doesn't mess with non-SkyBlock worlds played with the mod installed (so it does nothing by default, like Carpet). The problem with a default in the config folder is that this would also apply to non-SkyBlock worlds, which is why I went with the option to generate a config file if SkyBlock worldgen is chosen unless configs already exist.

I think the best fix to this issue would by merging the default configs and generated configs when the config is created, with priority given to the default config. This would mean all Carpet settings like `hopperCounters true` would be read from the default config, while still enabling `renewableSponges` unless specifically disabled in the default Carpet config.
