### ISSUE TITLE
[Feature Request] Other tree starts

### ISSUE THREAD

**Issue by Sir-Slimestone** [jsorrell/CarpetSkyAdditions#64]
The mod generates oak by default, has an optional datapack for acacia which I assume is because Ilmango went acacia, but what about the other trees. What if someone wants to do birch or spruce for example, effectively the same difficulty as acacia, but allows for a different wood texture and acacia also has that weird generation that some people hate chopping down. As a workaround is there something that can be changed in the optional acacia datapack to get a different tree type?

**Comment by jsorrell** [comment]
I don't really want to embed a bunch of different datapacks for each tree type because it will just add bloat to the datapack selection screen.

If you don't want to just switch into creative and swap the tree out, you can create a datapack that overrides `data/carpetskyadditions/structures/spawn_platform.nbt` with a structure file of the spawn platform. You can create the structure file using structure blocks.

**Comment by jsorrell** [comment]
[spawn_platform_structure_files.zip](https://github.com/jsorrell/CarpetSkyAdditions/files/9782999/spawn_platform_structure_files.zip)

Here's a zip file of birch, spruce, and jungle tree start structure files

**Comment by Sir-Slimestone** [comment]
Epic, good solution to avoid bloat, the structure block nbt idea also
allows for more creative starts! Thanks for the zip with the different trees
