### ISSUE TITLE
Problem with mini HUD mod

### ISSUE THREAD

**Issue by PHNX2** [jsorrell/CarpetSkyAdditions#74]
I just tried to make a server with this mod to get a skyblock world, following the instructions.
Everything works, appart one important thing : i can /tp to the structures (like the wich hut for example), and their mechanics work, but there I don't see them with MiniHUD mod...
Any idea ?

Thanks

**Comment by jsorrell** [comment]
According to [minihud](https://www.curseforge.com/minecraft/mc-mods/minihud), structure bounding boxes only work in single player, without a server-side mod. You also need the Servux mod.

**Comment by Kolya85** [comment]
Hello @jsorrell, 
A week ago I created a skyblock again with CarpetSkyAdditions in 1.19.2, everything works correctly except the MiniHUD bounding boxes.
It is a single player with several mods, all in their latest version for Minecraft 1.19.2 Fabric loader 0.14.14-1.19.2
It turns out that in the Skyblock generated with CarpetSkyAdditions I can't get the bounding boxes to show, but if I generate a normal world with the same Seed, they work correctly; What's more, in a Skyblock world also in 1.19.2 generated last year, this problem does not reproduce, even having exactly the same mods.

Any ideas why I can't see the bounding boxes in this skyblock?
[Mods list.txt](https://github.com/jsorrell/CarpetSkyAdditions/files/14313834/Mods.list.txt)
