### ISSUE TITLE
Customize the spawn platform?

### ISSUE THREAD

**Issue by Usercyk** [jsorrell/CarpetSkyAdditions#93]
1.18.2
Could I customize the spawn platform? And how can I do that?
For example, remove the nyliums, only 9 grass block, change the position of y-axis to -64......
Now I need to build the platform in creative mode every time I create a new world...That's too inconvenient.

**Comment by jsorrell** [comment]
A datapack overriding `skyblock/structures/spawn_platform.nbt` (`carpetskyadditions/structures/spawn_platform.nbt` since 4.1.0) with a structure file will change the spawn platform.

The origin of the platform is currently hardcoded as -(4,1,1) from the worldspawn, so it can't be lowered.

You'll have to run a "clone move" command to lower it. You can do this using the tick function of datapacks to run when the world first loads. I can help you with this if you want.

**Comment by jsorrell** [comment]
In future versions I'll add a way to customize where the spawn platform spawns in relation to the world spawn or in absolute position.

**Comment by Usercyk** [comment]
Oh thank you.
I know nothing about the tick function, so could you help me about this, please？
And is the nbt file created by the structure block?

**Comment by jsorrell** [comment]
Here is a datapack that should work for most spawn platforms. It essentially moves a 20 block square around the worldspawn down to -64 and tp's the player down. It uses the scoreboard to only do this on the first tick of the world.

The nbt file is placed into your `[world folder]/generated` when you save your structure with a structure file.
Replace `data/skyblock/structures/spawn_platform.nbt` in the datapack with the structure file for your spawn platform.

You can disable this datapack after the first tick of the world if you want.

[skyblock_lowerspawn.zip](https://github.com/jsorrell/CarpetSkyAdditions/files/10788270/skyblock_lowerspawn.zip)

**Comment by Usercyk** [comment]
Many thanks for your kind and warm help.
